apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stateless-web
  template:
    metadata:
      labels:
        app: stateless-web
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
